### ISSUE TITLE
metrics.js - /admin/metrics : No longer working

### ISSUE THREAD

**Issue by syepes** [ratpack/example-books#21]
Hello,

The example dashboard is not working as the JSON data returned by MetricsWebsocketBroadcastHandler is no longer matching the needed values in metrics.js

**Comment by alkemist** [comment]
@rhart might be time for some geb tests.

**Comment by rhart** [comment]
@syepes are you using master or latest?  I believe this to be fixed in latest.  It will get merged to master as part of the next release

**Comment by rhart** [comment]
@alkemist I think Geb testing the google charts will be difficult.  Defo time for some functional web socket tests though I think

**Comment by syepes** [comment]
@rhart Yes, the branch latest works correctly. Thanks

**Comment by rhart** [comment]
Thanks for raising the issue though.  If you fancy adding functional tests for the metrics that would be awesome ;)
